#pragma config(Motor,  port2,           primaryMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           secondaryMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
wait(0.5);
motor[primaryMotor] = 127;
motor[secondaryMotor] = 35;
wait(0.5);
motor[primaryMotor] = 127;
motor[secondaryMotor] = 0;
wait(0.5);
motor[primaryMotor] = 127;
motor[secondaryMotor] = -35;
wait(0.5);
motor[primaryMotor] = 127;
motor[secondaryMotor] = 35;
wait(0.5);
motor[primaryMotor] = 127;
wait(25);
}
